# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fcc_nn/fcc_nn.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcc_nn || ORIG_REF_NAME==fcc_nn} -quiet] -quiet

# IP: bd/fcc_nn/ip/fcc_nn_processing_system7_0_0/fcc_nn_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcc_nn_processing_system7_0_0 || ORIG_REF_NAME==fcc_nn_processing_system7_0_0} -quiet] -quiet

# IP: bd/fcc_nn/ip/fcc_nn_forward_fcc_0_0/fcc_nn_forward_fcc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcc_nn_forward_fcc_0_0 || ORIG_REF_NAME==fcc_nn_forward_fcc_0_0} -quiet] -quiet

# IP: bd/fcc_nn/ip/fcc_nn_ps7_0_axi_periph_0/fcc_nn_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcc_nn_ps7_0_axi_periph_0 || ORIG_REF_NAME==fcc_nn_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/fcc_nn/ip/fcc_nn_rst_ps7_0_100M_0/fcc_nn_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcc_nn_rst_ps7_0_100M_0 || ORIG_REF_NAME==fcc_nn_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/fcc_nn/ip/fcc_nn_axi_mem_intercon_1/fcc_nn_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcc_nn_axi_mem_intercon_1 || ORIG_REF_NAME==fcc_nn_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/fcc_nn/ip/fcc_nn_xbar_0/fcc_nn_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcc_nn_xbar_0 || ORIG_REF_NAME==fcc_nn_xbar_0} -quiet] -quiet

# IP: bd/fcc_nn/ip/fcc_nn_axi_gpio_0_0/fcc_nn_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcc_nn_axi_gpio_0_0 || ORIG_REF_NAME==fcc_nn_axi_gpio_0_0} -quiet] -quiet

# IP: bd/fcc_nn/ip/fcc_nn_axi_gpio_1_0/fcc_nn_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcc_nn_axi_gpio_1_0 || ORIG_REF_NAME==fcc_nn_axi_gpio_1_0} -quiet] -quiet

# IP: bd/fcc_nn/ip/fcc_nn_auto_pc_0/fcc_nn_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcc_nn_auto_pc_0 || ORIG_REF_NAME==fcc_nn_auto_pc_0} -quiet] -quiet

# IP: bd/fcc_nn/ip/fcc_nn_auto_pc_1/fcc_nn_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcc_nn_auto_pc_1 || ORIG_REF_NAME==fcc_nn_auto_pc_1} -quiet] -quiet

# XDC: bd/fcc_nn/fcc_nn_ooc.xdc
