# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/anubhav/workspace-2019/neural_net/neural_net.srcs/sources_1/bd/fcc_nn/ip/fcc_nn_xbar_0/fcc_nn_xbar_0.xci
# IP: The module: 'fcc_nn_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anubhav/workspace-2019/neural_net/neural_net.srcs/sources_1/bd/fcc_nn/ip/fcc_nn_xbar_0/fcc_nn_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fcc_nn_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/anubhav/workspace-2019/neural_net/neural_net.srcs/sources_1/bd/fcc_nn/ip/fcc_nn_xbar_0/fcc_nn_xbar_0.xci
# IP: The module: 'fcc_nn_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anubhav/workspace-2019/neural_net/neural_net.srcs/sources_1/bd/fcc_nn/ip/fcc_nn_xbar_0/fcc_nn_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fcc_nn_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
